"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright (C) 2021 Intel Corporation
SPDX-License-Identifier: Apache-2.0

Major pieces taken from:
https://github.com/ligato/cn-infra/blob/master/examples/cryptodata-proto-plugin/ipsec/ipsec.proto
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CryptoAlgorithm:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CryptoAlgorithmEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CryptoAlgorithm.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE_CRYPTO: _CryptoAlgorithm.ValueType  # 0
    AES128: _CryptoAlgorithm.ValueType  # 1
    AES192: _CryptoAlgorithm.ValueType  # 2
    AES256: _CryptoAlgorithm.ValueType  # 3
    AES128GCM128: _CryptoAlgorithm.ValueType  # 4
    AES256GCM128: _CryptoAlgorithm.ValueType  # 5
    AES128GMAC: _CryptoAlgorithm.ValueType  # 6
    AES256GMAC: _CryptoAlgorithm.ValueType  # 7

class CryptoAlgorithm(_CryptoAlgorithm, metaclass=_CryptoAlgorithmEnumTypeWrapper):
    """Cryptographic algorithm for encryption"""

NONE_CRYPTO: CryptoAlgorithm.ValueType  # 0
AES128: CryptoAlgorithm.ValueType  # 1
AES192: CryptoAlgorithm.ValueType  # 2
AES256: CryptoAlgorithm.ValueType  # 3
AES128GCM128: CryptoAlgorithm.ValueType  # 4
AES256GCM128: CryptoAlgorithm.ValueType  # 5
AES128GMAC: CryptoAlgorithm.ValueType  # 6
AES256GMAC: CryptoAlgorithm.ValueType  # 7
global___CryptoAlgorithm = CryptoAlgorithm

class _IntegAlgorithm:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IntegAlgorithmEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IntegAlgorithm.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE_INTEG: _IntegAlgorithm.ValueType  # 0
    MD5: _IntegAlgorithm.ValueType  # 1
    MD5_128: _IntegAlgorithm.ValueType  # 2
    SHA1: _IntegAlgorithm.ValueType  # 3
    SHA1_160: _IntegAlgorithm.ValueType  # 4
    SHA256: _IntegAlgorithm.ValueType  # 5
    SHA384: _IntegAlgorithm.ValueType  # 7
    SHA512: _IntegAlgorithm.ValueType  # 8
    SHA256_96: _IntegAlgorithm.ValueType  # 9

class IntegAlgorithm(_IntegAlgorithm, metaclass=_IntegAlgorithmEnumTypeWrapper):
    """Cryptographic algorithm for authentication"""

NONE_INTEG: IntegAlgorithm.ValueType  # 0
MD5: IntegAlgorithm.ValueType  # 1
MD5_128: IntegAlgorithm.ValueType  # 2
SHA1: IntegAlgorithm.ValueType  # 3
SHA1_160: IntegAlgorithm.ValueType  # 4
SHA256: IntegAlgorithm.ValueType  # 5
SHA384: IntegAlgorithm.ValueType  # 7
SHA512: IntegAlgorithm.ValueType  # 8
SHA256_96: IntegAlgorithm.ValueType  # 9
global___IntegAlgorithm = IntegAlgorithm

class _DiffieHellmanGroups:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DiffieHellmanGroupsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DiffieHellmanGroups.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE_DH_GROUP: _DiffieHellmanGroups.ValueType  # 0
    MODP768: _DiffieHellmanGroups.ValueType  # 1
    MODP1024: _DiffieHellmanGroups.ValueType  # 2
    MODP1536: _DiffieHellmanGroups.ValueType  # 3
    MODP2048: _DiffieHellmanGroups.ValueType  # 4
    MODP3072: _DiffieHellmanGroups.ValueType  # 5
    MODP4096: _DiffieHellmanGroups.ValueType  # 6
    MODP6144: _DiffieHellmanGroups.ValueType  # 7
    MODP8192: _DiffieHellmanGroups.ValueType  # 8
    MODP1024S160: _DiffieHellmanGroups.ValueType  # 9
    MODP2048S224: _DiffieHellmanGroups.ValueType  # 10
    MODP2048S256: _DiffieHellmanGroups.ValueType  # 11
    CURVE25519: _DiffieHellmanGroups.ValueType  # 12

class DiffieHellmanGroups(_DiffieHellmanGroups, metaclass=_DiffieHellmanGroupsEnumTypeWrapper):
    """Diffie Hellman Groups"""

NONE_DH_GROUP: DiffieHellmanGroups.ValueType  # 0
MODP768: DiffieHellmanGroups.ValueType  # 1
MODP1024: DiffieHellmanGroups.ValueType  # 2
MODP1536: DiffieHellmanGroups.ValueType  # 3
MODP2048: DiffieHellmanGroups.ValueType  # 4
MODP3072: DiffieHellmanGroups.ValueType  # 5
MODP4096: DiffieHellmanGroups.ValueType  # 6
MODP6144: DiffieHellmanGroups.ValueType  # 7
MODP8192: DiffieHellmanGroups.ValueType  # 8
MODP1024S160: DiffieHellmanGroups.ValueType  # 9
MODP2048S224: DiffieHellmanGroups.ValueType  # 10
MODP2048S256: DiffieHellmanGroups.ValueType  # 11
CURVE25519: DiffieHellmanGroups.ValueType  # 12
global___DiffieHellmanGroups = DiffieHellmanGroups

class _PseudoRandomFunction:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PseudoRandomFunctionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PseudoRandomFunction.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE_PRF: _PseudoRandomFunction.ValueType  # 0
    PRFMD5: _PseudoRandomFunction.ValueType  # 1
    PRFSHA1: _PseudoRandomFunction.ValueType  # 2
    PRFAESXCBC: _PseudoRandomFunction.ValueType  # 3
    PRFAESCMAC: _PseudoRandomFunction.ValueType  # 4
    PRFSHA256: _PseudoRandomFunction.ValueType  # 5
    PRFSHA384: _PseudoRandomFunction.ValueType  # 6
    PRFSHA512: _PseudoRandomFunction.ValueType  # 7

class PseudoRandomFunction(_PseudoRandomFunction, metaclass=_PseudoRandomFunctionEnumTypeWrapper): ...

NONE_PRF: PseudoRandomFunction.ValueType  # 0
PRFMD5: PseudoRandomFunction.ValueType  # 1
PRFSHA1: PseudoRandomFunction.ValueType  # 2
PRFAESXCBC: PseudoRandomFunction.ValueType  # 3
PRFAESCMAC: PseudoRandomFunction.ValueType  # 4
PRFSHA256: PseudoRandomFunction.ValueType  # 5
PRFSHA384: PseudoRandomFunction.ValueType  # 6
PRFSHA512: PseudoRandomFunction.ValueType  # 7
global___PseudoRandomFunction = PseudoRandomFunction

class _IPsecMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IPsecModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IPsecMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TUNNEL_MODE: _IPsecMode.ValueType  # 0
    TRANSPORT_MODE: _IPsecMode.ValueType  # 1

class IPsecMode(_IPsecMode, metaclass=_IPsecModeEnumTypeWrapper):
    """Tunnel mode"""

TUNNEL_MODE: IPsecMode.ValueType  # 0
TRANSPORT_MODE: IPsecMode.ValueType  # 1
global___IPsecMode = IPsecMode

class _AuthType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PUBKEY: _AuthType.ValueType  # 0
    PSK: _AuthType.ValueType  # 1
    XAUTH: _AuthType.ValueType  # 2
    EAP: _AuthType.ValueType  # 3

class AuthType(_AuthType, metaclass=_AuthTypeEnumTypeWrapper):
    """Authentication Type"""

PUBKEY: AuthType.ValueType  # 0
PSK: AuthType.ValueType  # 1
XAUTH: AuthType.ValueType  # 2
EAP: AuthType.ValueType  # 3
global___AuthType = AuthType

class _IkeSaState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IkeSaStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IkeSaState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CREATED: _IkeSaState.ValueType  # 0
    CONNECTING: _IkeSaState.ValueType  # 1
    ESTABLISHED: _IkeSaState.ValueType  # 2
    PASSIVE: _IkeSaState.ValueType  # 3
    REKEYING: _IkeSaState.ValueType  # 4
    REKEYED: _IkeSaState.ValueType  # 5
    DELETING: _IkeSaState.ValueType  # 6
    DESTROYING: _IkeSaState.ValueType  # 7

class IkeSaState(_IkeSaState, metaclass=_IkeSaStateEnumTypeWrapper):
    """IKE_SA state"""

CREATED: IkeSaState.ValueType  # 0
CONNECTING: IkeSaState.ValueType  # 1
ESTABLISHED: IkeSaState.ValueType  # 2
PASSIVE: IkeSaState.ValueType  # 3
REKEYING: IkeSaState.ValueType  # 4
REKEYED: IkeSaState.ValueType  # 5
DELETING: IkeSaState.ValueType  # 6
DESTROYING: IkeSaState.ValueType  # 7
global___IkeSaState = IkeSaState

class _ChildSaState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChildSaStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChildSaState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHILD_CREATED: _ChildSaState.ValueType  # 0
    CHILD_ROUTED: _ChildSaState.ValueType  # 1
    CHILD_INSTALLING: _ChildSaState.ValueType  # 2
    CHILD_INSTALLED: _ChildSaState.ValueType  # 3
    CHILD_UPDATING: _ChildSaState.ValueType  # 4
    CHILD_REKEYING: _ChildSaState.ValueType  # 5
    CHILD_REKEYED: _ChildSaState.ValueType  # 6
    CHILD_RETRYING: _ChildSaState.ValueType  # 7
    CHILD_DELETING: _ChildSaState.ValueType  # 8
    CHILD_DELETED: _ChildSaState.ValueType  # 9
    CHILD_DESTROYING: _ChildSaState.ValueType  # 10

class ChildSaState(_ChildSaState, metaclass=_ChildSaStateEnumTypeWrapper):
    """CHILD_SA state"""

CHILD_CREATED: ChildSaState.ValueType  # 0
CHILD_ROUTED: ChildSaState.ValueType  # 1
CHILD_INSTALLING: ChildSaState.ValueType  # 2
CHILD_INSTALLED: ChildSaState.ValueType  # 3
CHILD_UPDATING: ChildSaState.ValueType  # 4
CHILD_REKEYING: ChildSaState.ValueType  # 5
CHILD_REKEYED: ChildSaState.ValueType  # 6
CHILD_RETRYING: ChildSaState.ValueType  # 7
CHILD_DELETING: ChildSaState.ValueType  # 8
CHILD_DELETED: ChildSaState.ValueType  # 9
CHILD_DESTROYING: ChildSaState.ValueType  # 10
global___ChildSaState = ChildSaState

class _CertificateType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CertificateTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CertificateType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CERT_X509: _CertificateType.ValueType  # 0
    CERT_X509_AC: _CertificateType.ValueType  # 1
    CERT_X509_CRL: _CertificateType.ValueType  # 2
    CERT_OCSP_RESPONSE: _CertificateType.ValueType  # 3
    CERT_PUBKEY: _CertificateType.ValueType  # 4

class CertificateType(_CertificateType, metaclass=_CertificateTypeEnumTypeWrapper):
    """Certificate type"""

CERT_X509: CertificateType.ValueType  # 0
CERT_X509_AC: CertificateType.ValueType  # 1
CERT_X509_CRL: CertificateType.ValueType  # 2
CERT_OCSP_RESPONSE: CertificateType.ValueType  # 3
CERT_PUBKEY: CertificateType.ValueType  # 4
global___CertificateType = CertificateType

class _X509CertificateFlag:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _X509CertificateFlagEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_X509CertificateFlag.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    X509_CERT_FLAG_NONE: _X509CertificateFlag.ValueType  # 0
    X509_CERT_FLAG_CA: _X509CertificateFlag.ValueType  # 1
    X509_CERT_FLAG_AA: _X509CertificateFlag.ValueType  # 2
    X509_CERT_FLAG_OCSP: _X509CertificateFlag.ValueType  # 3

class X509CertificateFlag(_X509CertificateFlag, metaclass=_X509CertificateFlagEnumTypeWrapper):
    """X.509 certificate flag"""

X509_CERT_FLAG_NONE: X509CertificateFlag.ValueType  # 0
X509_CERT_FLAG_CA: X509CertificateFlag.ValueType  # 1
X509_CERT_FLAG_AA: X509CertificateFlag.ValueType  # 2
X509_CERT_FLAG_OCSP: X509CertificateFlag.ValueType  # 3
global___X509CertificateFlag = X509CertificateFlag

@typing_extensions.final
class Proposals(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CRYPTO_ALG_FIELD_NUMBER: builtins.int
    INTEG_ALG_FIELD_NUMBER: builtins.int
    PRF_FIELD_NUMBER: builtins.int
    DHGROUPS_FIELD_NUMBER: builtins.int
    @property
    def crypto_alg(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___CryptoAlgorithm.ValueType]: ...
    @property
    def integ_alg(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___IntegAlgorithm.ValueType]: ...
    @property
    def prf(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___PseudoRandomFunction.ValueType]: ...
    @property
    def dhgroups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DiffieHellmanGroups.ValueType]: ...
    def __init__(
        self,
        *,
        crypto_alg: collections.abc.Iterable[global___CryptoAlgorithm.ValueType] | None = ...,
        integ_alg: collections.abc.Iterable[global___IntegAlgorithm.ValueType] | None = ...,
        prf: collections.abc.Iterable[global___PseudoRandomFunction.ValueType] | None = ...,
        dhgroups: collections.abc.Iterable[global___DiffieHellmanGroups.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["crypto_alg", b"crypto_alg", "dhgroups", b"dhgroups", "integ_alg", b"integ_alg", "prf", b"prf"]) -> None: ...

global___Proposals = Proposals

@typing_extensions.final
class Vips(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIP_FIELD_NUMBER: builtins.int
    @property
    def vip(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        vip: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["vip", b"vip"]) -> None: ...

global___Vips = Vips

@typing_extensions.final
class Pools(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        pool: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pool", b"pool"]) -> None: ...

global___Pools = Pools

@typing_extensions.final
class Certs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERT_FIELD_NUMBER: builtins.int
    @property
    def cert(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        cert: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cert", b"cert"]) -> None: ...

global___Certs = Certs

@typing_extensions.final
class PubKeys(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBKEY_FIELD_NUMBER: builtins.int
    @property
    def pubkey(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        pubkey: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pubkey", b"pubkey"]) -> None: ...

global___PubKeys = PubKeys

@typing_extensions.final
class Groups(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROUP_FIELD_NUMBER: builtins.int
    @property
    def group(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        group: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["group", b"group"]) -> None: ...

global___Groups = Groups

@typing_extensions.final
class CertPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERT_POLICY_FIELD_NUMBER: builtins.int
    @property
    def cert_policy(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        cert_policy: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cert_policy", b"cert_policy"]) -> None: ...

global___CertPolicy = CertPolicy

@typing_extensions.final
class CaCerts(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CACERT_FIELD_NUMBER: builtins.int
    @property
    def cacert(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        cacert: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cacert", b"cacert"]) -> None: ...

global___CaCerts = CaCerts

@typing_extensions.final
class LocalAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTH_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    EAP_ID_FIELD_NUMBER: builtins.int
    AAA_ID_FIELD_NUMBER: builtins.int
    XAUTH_ID_FIELD_NUMBER: builtins.int
    CERTS_FIELD_NUMBER: builtins.int
    PUBKEYS_FIELD_NUMBER: builtins.int
    auth: global___AuthType.ValueType
    id: builtins.str
    eap_id: builtins.str
    aaa_id: builtins.str
    xauth_id: builtins.str
    @property
    def certs(self) -> global___Certs: ...
    @property
    def pubkeys(self) -> global___PubKeys: ...
    def __init__(
        self,
        *,
        auth: global___AuthType.ValueType = ...,
        id: builtins.str = ...,
        eap_id: builtins.str = ...,
        aaa_id: builtins.str = ...,
        xauth_id: builtins.str = ...,
        certs: global___Certs | None = ...,
        pubkeys: global___PubKeys | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["certs", b"certs", "pubkeys", b"pubkeys"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aaa_id", b"aaa_id", "auth", b"auth", "certs", b"certs", "eap_id", b"eap_id", "id", b"id", "pubkeys", b"pubkeys", "xauth_id", b"xauth_id"]) -> None: ...

global___LocalAuth = LocalAuth

@typing_extensions.final
class RemoteAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTH_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    EAP_ID_FIELD_NUMBER: builtins.int
    GROUPS_FIELD_NUMBER: builtins.int
    CERT_POLICY_FIELD_NUMBER: builtins.int
    CERTS_FIELD_NUMBER: builtins.int
    CA_CERTS_FIELD_NUMBER: builtins.int
    PUBKEYS_FIELD_NUMBER: builtins.int
    auth: global___AuthType.ValueType
    id: builtins.str
    eap_id: builtins.str
    @property
    def groups(self) -> global___Groups: ...
    @property
    def cert_policy(self) -> global___CertPolicy: ...
    @property
    def certs(self) -> global___Certs: ...
    @property
    def ca_certs(self) -> global___CaCerts: ...
    @property
    def pubkeys(self) -> global___PubKeys: ...
    def __init__(
        self,
        *,
        auth: global___AuthType.ValueType = ...,
        id: builtins.str = ...,
        eap_id: builtins.str = ...,
        groups: global___Groups | None = ...,
        cert_policy: global___CertPolicy | None = ...,
        certs: global___Certs | None = ...,
        ca_certs: global___CaCerts | None = ...,
        pubkeys: global___PubKeys | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ca_certs", b"ca_certs", "cert_policy", b"cert_policy", "certs", b"certs", "groups", b"groups", "pubkeys", b"pubkeys"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth", b"auth", "ca_certs", b"ca_certs", "cert_policy", b"cert_policy", "certs", b"certs", "eap_id", b"eap_id", "groups", b"groups", "id", b"id", "pubkeys", b"pubkeys"]) -> None: ...

global___RemoteAuth = RemoteAuth

@typing_extensions.final
class TrafficSelectors(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class TrafficSelector(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CIDR_FIELD_NUMBER: builtins.int
        PROTO_FIELD_NUMBER: builtins.int
        PORT_FIELD_NUMBER: builtins.int
        cidr: builtins.str
        proto: builtins.str
        port: builtins.str
        def __init__(
            self,
            *,
            cidr: builtins.str = ...,
            proto: builtins.str = ...,
            port: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["cidr", b"cidr", "port", b"port", "proto", b"proto"]) -> None: ...

    TS_FIELD_NUMBER: builtins.int
    @property
    def ts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrafficSelectors.TrafficSelector]: ...
    def __init__(
        self,
        *,
        ts: collections.abc.Iterable[global___TrafficSelectors.TrafficSelector] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ts", b"ts"]) -> None: ...

global___TrafficSelectors = TrafficSelectors

@typing_extensions.final
class Addrs(google.protobuf.message.Message):
    """IP addresses or hostanmes"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDR_FIELD_NUMBER: builtins.int
    addr: builtins.str
    def __init__(
        self,
        *,
        addr: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addr", b"addr"]) -> None: ...

global___Addrs = Addrs

@typing_extensions.final
class Child(google.protobuf.message.Message):
    """Child SA"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    AG_PROPOSALS_FIELD_NUMBER: builtins.int
    ESP_PROPOSALS_FIELD_NUMBER: builtins.int
    LOCAL_TS_FIELD_NUMBER: builtins.int
    REMOTE_TS_FIELD_NUMBER: builtins.int
    REKEY_TIME_FIELD_NUMBER: builtins.int
    LIFE_TIME_FIELD_NUMBER: builtins.int
    RAND_TIME_FIELD_NUMBER: builtins.int
    UPDOWN_FIELD_NUMBER: builtins.int
    INACTIVITY_FIELD_NUMBER: builtins.int
    MARK_IN_FIELD_NUMBER: builtins.int
    MARK_IN_SA_FIELD_NUMBER: builtins.int
    MARK_OUT_FIELD_NUMBER: builtins.int
    SET_MARK_IN_FIELD_NUMBER: builtins.int
    SET_MARK_OUT_FIELD_NUMBER: builtins.int
    HW_OFFLOAD_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Child SA name"""
    @property
    def ag_proposals(self) -> global___Proposals: ...
    @property
    def esp_proposals(self) -> global___Proposals: ...
    @property
    def local_ts(self) -> global___TrafficSelectors: ...
    @property
    def remote_ts(self) -> global___TrafficSelectors: ...
    rekey_time: builtins.int
    life_time: builtins.int
    rand_time: builtins.int
    updown: builtins.str
    inactivity: builtins.int
    mark_in: builtins.int
    mark_in_sa: builtins.str
    mark_out: builtins.int
    set_mark_in: builtins.int
    set_mark_out: builtins.int
    hw_offload: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        ag_proposals: global___Proposals | None = ...,
        esp_proposals: global___Proposals | None = ...,
        local_ts: global___TrafficSelectors | None = ...,
        remote_ts: global___TrafficSelectors | None = ...,
        rekey_time: builtins.int = ...,
        life_time: builtins.int = ...,
        rand_time: builtins.int = ...,
        updown: builtins.str = ...,
        inactivity: builtins.int = ...,
        mark_in: builtins.int = ...,
        mark_in_sa: builtins.str = ...,
        mark_out: builtins.int = ...,
        set_mark_in: builtins.int = ...,
        set_mark_out: builtins.int = ...,
        hw_offload: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ag_proposals", b"ag_proposals", "esp_proposals", b"esp_proposals", "local_ts", b"local_ts", "remote_ts", b"remote_ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ag_proposals", b"ag_proposals", "esp_proposals", b"esp_proposals", "hw_offload", b"hw_offload", "inactivity", b"inactivity", "life_time", b"life_time", "local_ts", b"local_ts", "mark_in", b"mark_in", "mark_in_sa", b"mark_in_sa", "mark_out", b"mark_out", "name", b"name", "rand_time", b"rand_time", "rekey_time", b"rekey_time", "remote_ts", b"remote_ts", "set_mark_in", b"set_mark_in", "set_mark_out", b"set_mark_out", "updown", b"updown"]) -> None: ...

global___Child = Child

@typing_extensions.final
class Connection(google.protobuf.message.Message):
    """IKE connection"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    LOCAL_ADDRS_FIELD_NUMBER: builtins.int
    REMOTE_ADDRS_FIELD_NUMBER: builtins.int
    LOCAL_PORT_FIELD_NUMBER: builtins.int
    REMOTE_PORT_FIELD_NUMBER: builtins.int
    PROPOSALS_FIELD_NUMBER: builtins.int
    VIPS_FIELD_NUMBER: builtins.int
    DSCP_FIELD_NUMBER: builtins.int
    ENCAP_FIELD_NUMBER: builtins.int
    MOBIKE_FIELD_NUMBER: builtins.int
    DPD_DELAY_FIELD_NUMBER: builtins.int
    DPD_TIMEOUT_FIELD_NUMBER: builtins.int
    REAUTH_TIME_FIELD_NUMBER: builtins.int
    REKEY_TIME_FIELD_NUMBER: builtins.int
    POOLS_FIELD_NUMBER: builtins.int
    LOCAL_AUTH_FIELD_NUMBER: builtins.int
    REMOTE_AUTH_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    name: builtins.str
    """connection name"""
    version: builtins.str
    @property
    def local_addrs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addrs]: ...
    @property
    def remote_addrs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addrs]: ...
    local_port: builtins.int
    remote_port: builtins.int
    @property
    def proposals(self) -> global___Proposals: ...
    @property
    def vips(self) -> global___Vips: ...
    dscp: builtins.int
    """We use only the lower 6 bytes"""
    encap: builtins.str
    mobike: builtins.str
    dpd_delay: builtins.int
    dpd_timeout: builtins.int
    reauth_time: builtins.int
    rekey_time: builtins.int
    @property
    def pools(self) -> global___Pools: ...
    @property
    def local_auth(self) -> global___LocalAuth: ...
    @property
    def remote_auth(self) -> global___RemoteAuth: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Child]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
        local_addrs: collections.abc.Iterable[global___Addrs] | None = ...,
        remote_addrs: collections.abc.Iterable[global___Addrs] | None = ...,
        local_port: builtins.int = ...,
        remote_port: builtins.int = ...,
        proposals: global___Proposals | None = ...,
        vips: global___Vips | None = ...,
        dscp: builtins.int = ...,
        encap: builtins.str = ...,
        mobike: builtins.str = ...,
        dpd_delay: builtins.int = ...,
        dpd_timeout: builtins.int = ...,
        reauth_time: builtins.int = ...,
        rekey_time: builtins.int = ...,
        pools: global___Pools | None = ...,
        local_auth: global___LocalAuth | None = ...,
        remote_auth: global___RemoteAuth | None = ...,
        children: collections.abc.Iterable[global___Child] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["local_auth", b"local_auth", "pools", b"pools", "proposals", b"proposals", "remote_auth", b"remote_auth", "vips", b"vips"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["children", b"children", "dpd_delay", b"dpd_delay", "dpd_timeout", b"dpd_timeout", "dscp", b"dscp", "encap", b"encap", "local_addrs", b"local_addrs", "local_auth", b"local_auth", "local_port", b"local_port", "mobike", b"mobike", "name", b"name", "pools", b"pools", "proposals", b"proposals", "reauth_time", b"reauth_time", "rekey_time", b"rekey_time", "remote_addrs", b"remote_addrs", "remote_auth", b"remote_auth", "remote_port", b"remote_port", "version", b"version", "vips", b"vips"]) -> None: ...

global___Connection = Connection

@typing_extensions.final
class IPsecVersionReq(google.protobuf.message.Message):
    """Intentionally empty"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPsecVersionReq = IPsecVersionReq

@typing_extensions.final
class IPsecVersionResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DAEMON_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    SYSNAME_FIELD_NUMBER: builtins.int
    RELEASE_FIELD_NUMBER: builtins.int
    MACHINE_FIELD_NUMBER: builtins.int
    daemon: builtins.str
    version: builtins.str
    sysname: builtins.str
    release: builtins.str
    machine: builtins.str
    def __init__(
        self,
        *,
        daemon: builtins.str = ...,
        version: builtins.str = ...,
        sysname: builtins.str = ...,
        release: builtins.str = ...,
        machine: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["daemon", b"daemon", "machine", b"machine", "release", b"release", "sysname", b"sysname", "version", b"version"]) -> None: ...

global___IPsecVersionResp = IPsecVersionResp

@typing_extensions.final
class IPsecStatsReq(google.protobuf.message.Message):
    """Intentionally empty"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPsecStatsReq = IPsecStatsReq

@typing_extensions.final
class IPsecStatsResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    """Generic status string for now"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["status", b"status"]) -> None: ...

global___IPsecStatsResp = IPsecStatsResp

@typing_extensions.final
class IPsecInitiateReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHILD_FIELD_NUMBER: builtins.int
    IKE_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    LOGLEVEL_FIELD_NUMBER: builtins.int
    child: builtins.str
    ike: builtins.str
    timeout: builtins.str
    loglevel: builtins.str
    def __init__(
        self,
        *,
        child: builtins.str = ...,
        ike: builtins.str = ...,
        timeout: builtins.str = ...,
        loglevel: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["child", b"child", "ike", b"ike", "loglevel", b"loglevel", "timeout", b"timeout"]) -> None: ...

global___IPsecInitiateReq = IPsecInitiateReq

@typing_extensions.final
class IPsecInitiateResp(google.protobuf.message.Message):
    """Intentionally empty"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPsecInitiateResp = IPsecInitiateResp

@typing_extensions.final
class IPsecTerminateReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHILD_FIELD_NUMBER: builtins.int
    IKE_FIELD_NUMBER: builtins.int
    CHILD_ID_FIELD_NUMBER: builtins.int
    IKE_ID_FIELD_NUMBER: builtins.int
    FORCE_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    LOGLEVEL_FIELD_NUMBER: builtins.int
    child: builtins.str
    ike: builtins.str
    child_id: builtins.int
    ike_id: builtins.int
    force: builtins.str
    timeout: builtins.str
    loglevel: builtins.str
    def __init__(
        self,
        *,
        child: builtins.str = ...,
        ike: builtins.str = ...,
        child_id: builtins.int = ...,
        ike_id: builtins.int = ...,
        force: builtins.str = ...,
        timeout: builtins.str = ...,
        loglevel: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["child", b"child", "child_id", b"child_id", "force", b"force", "ike", b"ike", "ike_id", b"ike_id", "loglevel", b"loglevel", "timeout", b"timeout"]) -> None: ...

global___IPsecTerminateReq = IPsecTerminateReq

@typing_extensions.final
class IPsecTerminateResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MATCHES_FIELD_NUMBER: builtins.int
    TERMINATED_FIELD_NUMBER: builtins.int
    success: builtins.str
    matches: builtins.int
    terminated: builtins.int
    def __init__(
        self,
        *,
        success: builtins.str = ...,
        matches: builtins.int = ...,
        terminated: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["matches", b"matches", "success", b"success", "terminated", b"terminated"]) -> None: ...

global___IPsecTerminateResp = IPsecTerminateResp

@typing_extensions.final
class IPsecRekeyReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHILD_FIELD_NUMBER: builtins.int
    IKE_FIELD_NUMBER: builtins.int
    CHILD_ID_FIELD_NUMBER: builtins.int
    IKE_ID_FIELD_NUMBER: builtins.int
    REAUTH_FIELD_NUMBER: builtins.int
    child: builtins.str
    ike: builtins.str
    child_id: builtins.int
    ike_id: builtins.int
    reauth: builtins.str
    def __init__(
        self,
        *,
        child: builtins.str = ...,
        ike: builtins.str = ...,
        child_id: builtins.int = ...,
        ike_id: builtins.int = ...,
        reauth: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["child", b"child", "child_id", b"child_id", "ike", b"ike", "ike_id", b"ike_id", "reauth", b"reauth"]) -> None: ...

global___IPsecRekeyReq = IPsecRekeyReq

@typing_extensions.final
class IPsecRekeyResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MATCHES_FIELD_NUMBER: builtins.int
    success: builtins.str
    matches: builtins.int
    def __init__(
        self,
        *,
        success: builtins.str = ...,
        matches: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["matches", b"matches", "success", b"success"]) -> None: ...

global___IPsecRekeyResp = IPsecRekeyResp

@typing_extensions.final
class IPsecListSasReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOBLOCK_FIELD_NUMBER: builtins.int
    IKE_FIELD_NUMBER: builtins.int
    IKE_ID_FIELD_NUMBER: builtins.int
    CHILD_FIELD_NUMBER: builtins.int
    CHILD_ID_FIELD_NUMBER: builtins.int
    noblock: builtins.str
    ike: builtins.str
    ike_id: builtins.int
    child: builtins.str
    child_id: builtins.int
    def __init__(
        self,
        *,
        noblock: builtins.str = ...,
        ike: builtins.str = ...,
        ike_id: builtins.int = ...,
        child: builtins.str = ...,
        child_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["child", b"child", "child_id", b"child_id", "ike", b"ike", "ike_id", b"ike_id", "noblock", b"noblock"]) -> None: ...

global___IPsecListSasReq = IPsecListSasReq

@typing_extensions.final
class ListChildSa(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    ENCAP_FIELD_NUMBER: builtins.int
    SPI_IN_FIELD_NUMBER: builtins.int
    SPI_OUT_FIELD_NUMBER: builtins.int
    CPI_IN_FIELD_NUMBER: builtins.int
    CPI_OUT_FIELD_NUMBER: builtins.int
    MARK_IN_FIELD_NUMBER: builtins.int
    MARK_MASK_IN_FIELD_NUMBER: builtins.int
    MARK_OUT_FIELD_NUMBER: builtins.int
    MARK_MASK_OUT_FIELD_NUMBER: builtins.int
    IF_ID_IN_FIELD_NUMBER: builtins.int
    IF_ID_OUT_FIELD_NUMBER: builtins.int
    ENCR_ALG_FIELD_NUMBER: builtins.int
    ENCR_KEYSIZE_FIELD_NUMBER: builtins.int
    INTEG_ALG_FIELD_NUMBER: builtins.int
    INTEG_KEYSIZE_FIELD_NUMBER: builtins.int
    DH_GROUP_FIELD_NUMBER: builtins.int
    ESN_FIELD_NUMBER: builtins.int
    name: builtins.str
    protocol: builtins.str
    encap: builtins.str
    spi_in: builtins.str
    spi_out: builtins.str
    cpi_in: builtins.str
    cpi_out: builtins.str
    mark_in: builtins.str
    mark_mask_in: builtins.str
    mark_out: builtins.str
    mark_mask_out: builtins.str
    if_id_in: builtins.str
    if_id_out: builtins.str
    encr_alg: builtins.str
    encr_keysize: builtins.str
    integ_alg: builtins.str
    integ_keysize: builtins.str
    dh_group: builtins.str
    esn: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        protocol: builtins.str = ...,
        encap: builtins.str = ...,
        spi_in: builtins.str = ...,
        spi_out: builtins.str = ...,
        cpi_in: builtins.str = ...,
        cpi_out: builtins.str = ...,
        mark_in: builtins.str = ...,
        mark_mask_in: builtins.str = ...,
        mark_out: builtins.str = ...,
        mark_mask_out: builtins.str = ...,
        if_id_in: builtins.str = ...,
        if_id_out: builtins.str = ...,
        encr_alg: builtins.str = ...,
        encr_keysize: builtins.str = ...,
        integ_alg: builtins.str = ...,
        integ_keysize: builtins.str = ...,
        dh_group: builtins.str = ...,
        esn: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cpi_in", b"cpi_in", "cpi_out", b"cpi_out", "dh_group", b"dh_group", "encap", b"encap", "encr_alg", b"encr_alg", "encr_keysize", b"encr_keysize", "esn", b"esn", "if_id_in", b"if_id_in", "if_id_out", b"if_id_out", "integ_alg", b"integ_alg", "integ_keysize", b"integ_keysize", "mark_in", b"mark_in", "mark_mask_in", b"mark_mask_in", "mark_mask_out", b"mark_mask_out", "mark_out", b"mark_out", "name", b"name", "protocol", b"protocol", "spi_in", b"spi_in", "spi_out", b"spi_out"]) -> None: ...

global___ListChildSa = ListChildSa

@typing_extensions.final
class ListIkeSa(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    UNIQUEID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    IKESTATE_FIELD_NUMBER: builtins.int
    LOCAL_HOST_FIELD_NUMBER: builtins.int
    LOCAL_PORT_FIELD_NUMBER: builtins.int
    LOCAL_ID_FIELD_NUMBER: builtins.int
    REMOTE_HOST_FIELD_NUMBER: builtins.int
    REMOTE_PORT_FIELD_NUMBER: builtins.int
    REMOTE_ID_FIELD_NUMBER: builtins.int
    REMOTE_XAUTH_ID_FIELD_NUMBER: builtins.int
    REMOTE_EAP_ID_FIELD_NUMBER: builtins.int
    INITIATOR_FIELD_NUMBER: builtins.int
    INITIATOR_SPI_FIELD_NUMBER: builtins.int
    RESPONDER_SPI_FIELD_NUMBER: builtins.int
    NAT_LOCAL_FIELD_NUMBER: builtins.int
    NAT_REMOTE_FIELD_NUMBER: builtins.int
    NAT_FAKE_FIELD_NUMBER: builtins.int
    NAT_ANY_FIELD_NUMBER: builtins.int
    IF_ID_IN_FIELD_NUMBER: builtins.int
    IF_ID_OUT_FIELD_NUMBER: builtins.int
    ENCR_ALG_FIELD_NUMBER: builtins.int
    ENCR_KEYSIZE_FIELD_NUMBER: builtins.int
    INTEG_ALG_FIELD_NUMBER: builtins.int
    INTEG_KEYSIZE_FIELD_NUMBER: builtins.int
    PRF_ALG_FIELD_NUMBER: builtins.int
    DH_GROUP_FIELD_NUMBER: builtins.int
    PPK_FIELD_NUMBER: builtins.int
    ESTABLISHED_FIELD_NUMBER: builtins.int
    REKEY_TIME_FIELD_NUMBER: builtins.int
    REAUTH_TIME_FIELD_NUMBER: builtins.int
    LOCAL_VIPS_FIELD_NUMBER: builtins.int
    REMOTE_VIPS_FIELD_NUMBER: builtins.int
    TASKS_QUEUED_FIELD_NUMBER: builtins.int
    TASKS_ACTIVE_FIELD_NUMBER: builtins.int
    TASKS_PASSIVE_FIELD_NUMBER: builtins.int
    CHILDSAS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """IKE_SA name"""
    uniqueid: builtins.str
    version: builtins.str
    ikestate: global___IkeSaState.ValueType
    local_host: builtins.str
    local_port: builtins.str
    local_id: builtins.str
    remote_host: builtins.str
    remote_port: builtins.str
    remote_id: builtins.str
    remote_xauth_id: builtins.str
    remote_eap_id: builtins.str
    initiator: builtins.str
    initiator_spi: builtins.str
    responder_spi: builtins.str
    nat_local: builtins.str
    nat_remote: builtins.str
    nat_fake: builtins.str
    nat_any: builtins.str
    if_id_in: builtins.str
    if_id_out: builtins.str
    encr_alg: builtins.str
    encr_keysize: builtins.str
    integ_alg: builtins.str
    integ_keysize: builtins.str
    prf_alg: builtins.str
    dh_group: builtins.str
    ppk: builtins.str
    established: builtins.str
    rekey_time: builtins.str
    reauth_time: builtins.str
    @property
    def local_vips(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def remote_vips(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def tasks_queued(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def tasks_active(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def tasks_passive(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def childsas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListChildSa]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        uniqueid: builtins.str = ...,
        version: builtins.str = ...,
        ikestate: global___IkeSaState.ValueType = ...,
        local_host: builtins.str = ...,
        local_port: builtins.str = ...,
        local_id: builtins.str = ...,
        remote_host: builtins.str = ...,
        remote_port: builtins.str = ...,
        remote_id: builtins.str = ...,
        remote_xauth_id: builtins.str = ...,
        remote_eap_id: builtins.str = ...,
        initiator: builtins.str = ...,
        initiator_spi: builtins.str = ...,
        responder_spi: builtins.str = ...,
        nat_local: builtins.str = ...,
        nat_remote: builtins.str = ...,
        nat_fake: builtins.str = ...,
        nat_any: builtins.str = ...,
        if_id_in: builtins.str = ...,
        if_id_out: builtins.str = ...,
        encr_alg: builtins.str = ...,
        encr_keysize: builtins.str = ...,
        integ_alg: builtins.str = ...,
        integ_keysize: builtins.str = ...,
        prf_alg: builtins.str = ...,
        dh_group: builtins.str = ...,
        ppk: builtins.str = ...,
        established: builtins.str = ...,
        rekey_time: builtins.str = ...,
        reauth_time: builtins.str = ...,
        local_vips: collections.abc.Iterable[builtins.str] | None = ...,
        remote_vips: collections.abc.Iterable[builtins.str] | None = ...,
        tasks_queued: collections.abc.Iterable[builtins.str] | None = ...,
        tasks_active: collections.abc.Iterable[builtins.str] | None = ...,
        tasks_passive: collections.abc.Iterable[builtins.str] | None = ...,
        childsas: collections.abc.Iterable[global___ListChildSa] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["childsas", b"childsas", "dh_group", b"dh_group", "encr_alg", b"encr_alg", "encr_keysize", b"encr_keysize", "established", b"established", "if_id_in", b"if_id_in", "if_id_out", b"if_id_out", "ikestate", b"ikestate", "initiator", b"initiator", "initiator_spi", b"initiator_spi", "integ_alg", b"integ_alg", "integ_keysize", b"integ_keysize", "local_host", b"local_host", "local_id", b"local_id", "local_port", b"local_port", "local_vips", b"local_vips", "name", b"name", "nat_any", b"nat_any", "nat_fake", b"nat_fake", "nat_local", b"nat_local", "nat_remote", b"nat_remote", "ppk", b"ppk", "prf_alg", b"prf_alg", "reauth_time", b"reauth_time", "rekey_time", b"rekey_time", "remote_eap_id", b"remote_eap_id", "remote_host", b"remote_host", "remote_id", b"remote_id", "remote_port", b"remote_port", "remote_vips", b"remote_vips", "remote_xauth_id", b"remote_xauth_id", "responder_spi", b"responder_spi", "tasks_active", b"tasks_active", "tasks_passive", b"tasks_passive", "tasks_queued", b"tasks_queued", "uniqueid", b"uniqueid", "version", b"version"]) -> None: ...

global___ListIkeSa = ListIkeSa

@typing_extensions.final
class IPsecListSasResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IKESAS_FIELD_NUMBER: builtins.int
    @property
    def ikesas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListIkeSa]: ...
    def __init__(
        self,
        *,
        ikesas: collections.abc.Iterable[global___ListIkeSa] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ikesas", b"ikesas"]) -> None: ...

global___IPsecListSasResp = IPsecListSasResp

@typing_extensions.final
class IPsecListConnsReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IKE_FIELD_NUMBER: builtins.int
    ike: builtins.str
    def __init__(
        self,
        *,
        ike: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ike", b"ike"]) -> None: ...

global___IPsecListConnsReq = IPsecListConnsReq

@typing_extensions.final
class ListConnAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLASS_FIELD_NUMBER: builtins.int
    EAPTYPE_FIELD_NUMBER: builtins.int
    EAPVENDOR_FIELD_NUMBER: builtins.int
    XAUTH_FIELD_NUMBER: builtins.int
    REVOCATION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    CA_ID_FIELD_NUMBER: builtins.int
    AAA_ID_FIELD_NUMBER: builtins.int
    EAP_ID_FIELD_NUMBER: builtins.int
    XAUTH_ID_FIELD_NUMBER: builtins.int
    GROUP_FIELD_NUMBER: builtins.int
    CERT_POLICY_FIELD_NUMBER: builtins.int
    CERTS_FIELD_NUMBER: builtins.int
    CACERTS_FIELD_NUMBER: builtins.int
    eaptype: builtins.str
    eapvendor: builtins.str
    xauth: builtins.str
    revocation: builtins.str
    id: builtins.str
    ca_id: builtins.str
    aaa_id: builtins.str
    eap_id: builtins.str
    xauth_id: builtins.str
    @property
    def group(self) -> global___Groups: ...
    @property
    def cert_policy(self) -> global___CertPolicy: ...
    @property
    def certs(self) -> global___Certs: ...
    @property
    def cacerts(self) -> global___CaCerts: ...
    def __init__(
        self,
        *,
        eaptype: builtins.str = ...,
        eapvendor: builtins.str = ...,
        xauth: builtins.str = ...,
        revocation: builtins.str = ...,
        id: builtins.str = ...,
        ca_id: builtins.str = ...,
        aaa_id: builtins.str = ...,
        eap_id: builtins.str = ...,
        xauth_id: builtins.str = ...,
        group: global___Groups | None = ...,
        cert_policy: global___CertPolicy | None = ...,
        certs: global___Certs | None = ...,
        cacerts: global___CaCerts | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cacerts", b"cacerts", "cert_policy", b"cert_policy", "certs", b"certs", "group", b"group"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aaa_id", b"aaa_id", "ca_id", b"ca_id", "cacerts", b"cacerts", "cert_policy", b"cert_policy", "certs", b"certs", "class", b"class", "eap_id", b"eap_id", "eaptype", b"eaptype", "eapvendor", b"eapvendor", "group", b"group", "id", b"id", "revocation", b"revocation", "xauth", b"xauth", "xauth_id", b"xauth_id"]) -> None: ...

global___ListConnAuth = ListConnAuth

@typing_extensions.final
class ListChild(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    REKEY_TIME_FIELD_NUMBER: builtins.int
    REKEY_BYTES_FIELD_NUMBER: builtins.int
    REKEY_PACKETS_FIELD_NUMBER: builtins.int
    DPD_ACTION_FIELD_NUMBER: builtins.int
    CLOSE_ACTION_FIELD_NUMBER: builtins.int
    LOCAL_TS_FIELD_NUMBER: builtins.int
    REMOTE_TS_FIELD_NUMBER: builtins.int
    INTERFACE_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Child SA name"""
    mode: builtins.str
    label: builtins.str
    rekey_time: builtins.int
    rekey_bytes: builtins.int
    rekey_packets: builtins.int
    dpd_action: builtins.str
    close_action: builtins.str
    @property
    def local_ts(self) -> global___TrafficSelectors: ...
    @property
    def remote_ts(self) -> global___TrafficSelectors: ...
    interface: builtins.str
    priority: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        mode: builtins.str = ...,
        label: builtins.str = ...,
        rekey_time: builtins.int = ...,
        rekey_bytes: builtins.int = ...,
        rekey_packets: builtins.int = ...,
        dpd_action: builtins.str = ...,
        close_action: builtins.str = ...,
        local_ts: global___TrafficSelectors | None = ...,
        remote_ts: global___TrafficSelectors | None = ...,
        interface: builtins.str = ...,
        priority: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["local_ts", b"local_ts", "remote_ts", b"remote_ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["close_action", b"close_action", "dpd_action", b"dpd_action", "interface", b"interface", "label", b"label", "local_ts", b"local_ts", "mode", b"mode", "name", b"name", "priority", b"priority", "rekey_bytes", b"rekey_bytes", "rekey_packets", b"rekey_packets", "rekey_time", b"rekey_time", "remote_ts", b"remote_ts"]) -> None: ...

global___ListChild = ListChild

@typing_extensions.final
class ListConnResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    LOCAL_ADDRS_FIELD_NUMBER: builtins.int
    REMOTE_ADDRS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    REAUTH_TIME_FIELD_NUMBER: builtins.int
    REKEY_TIME_FIELD_NUMBER: builtins.int
    UNIQUE_FIELD_NUMBER: builtins.int
    DPD_DELAY_FIELD_NUMBER: builtins.int
    DPD_TIMEOUT_FIELD_NUMBER: builtins.int
    PPK_FIELD_NUMBER: builtins.int
    PPK_REQUIRED_FIELD_NUMBER: builtins.int
    LOCAL_AUTH_FIELD_NUMBER: builtins.int
    REMOTE_AUTH_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Connection name"""
    @property
    def local_addrs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addrs]: ...
    @property
    def remote_addrs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addrs]: ...
    version: builtins.str
    reauth_time: builtins.int
    rekey_time: builtins.int
    unique: builtins.str
    dpd_delay: builtins.int
    dpd_timeout: builtins.int
    ppk: builtins.str
    ppk_required: builtins.str
    @property
    def local_auth(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListConnAuth]: ...
    @property
    def remote_auth(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListConnAuth]: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListChild]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        local_addrs: collections.abc.Iterable[global___Addrs] | None = ...,
        remote_addrs: collections.abc.Iterable[global___Addrs] | None = ...,
        version: builtins.str = ...,
        reauth_time: builtins.int = ...,
        rekey_time: builtins.int = ...,
        unique: builtins.str = ...,
        dpd_delay: builtins.int = ...,
        dpd_timeout: builtins.int = ...,
        ppk: builtins.str = ...,
        ppk_required: builtins.str = ...,
        local_auth: collections.abc.Iterable[global___ListConnAuth] | None = ...,
        remote_auth: collections.abc.Iterable[global___ListConnAuth] | None = ...,
        children: collections.abc.Iterable[global___ListChild] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["children", b"children", "dpd_delay", b"dpd_delay", "dpd_timeout", b"dpd_timeout", "local_addrs", b"local_addrs", "local_auth", b"local_auth", "name", b"name", "ppk", b"ppk", "ppk_required", b"ppk_required", "reauth_time", b"reauth_time", "rekey_time", b"rekey_time", "remote_addrs", b"remote_addrs", "remote_auth", b"remote_auth", "unique", b"unique", "version", b"version"]) -> None: ...

global___ListConnResp = ListConnResp

@typing_extensions.final
class IPsecListConnsResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTION_FIELD_NUMBER: builtins.int
    @property
    def connection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListConnResp]: ...
    def __init__(
        self,
        *,
        connection: collections.abc.Iterable[global___ListConnResp] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["connection", b"connection"]) -> None: ...

global___IPsecListConnsResp = IPsecListConnsResp

@typing_extensions.final
class IPsecListCertsReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    type: builtins.str
    flag: builtins.str
    subject: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        flag: builtins.str = ...,
        subject: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["flag", b"flag", "subject", b"subject", "type", b"type"]) -> None: ...

global___IPsecListCertsReq = IPsecListCertsReq

@typing_extensions.final
class ListCert(google.protobuf.message.Message):
    """list-cert"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    HASPRIVKEY_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    NOTBEFORE_FIELD_NUMBER: builtins.int
    NOTAFTER_FIELD_NUMBER: builtins.int
    type: global___CertificateType.ValueType
    flag: global___X509CertificateFlag.ValueType
    hasprivkey: builtins.str
    data: builtins.str
    subject: builtins.str
    notbefore: builtins.str
    notafter: builtins.str
    def __init__(
        self,
        *,
        type: global___CertificateType.ValueType = ...,
        flag: global___X509CertificateFlag.ValueType = ...,
        hasprivkey: builtins.str = ...,
        data: builtins.str = ...,
        subject: builtins.str = ...,
        notbefore: builtins.str = ...,
        notafter: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "flag", b"flag", "hasprivkey", b"hasprivkey", "notafter", b"notafter", "notbefore", b"notbefore", "subject", b"subject", "type", b"type"]) -> None: ...

global___ListCert = ListCert

@typing_extensions.final
class IPsecListCertsResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERTS_FIELD_NUMBER: builtins.int
    @property
    def certs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListCert]: ...
    def __init__(
        self,
        *,
        certs: collections.abc.Iterable[global___ListCert] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["certs", b"certs"]) -> None: ...

global___IPsecListCertsResp = IPsecListCertsResp

@typing_extensions.final
class IPsecLoadConnReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTION_FIELD_NUMBER: builtins.int
    @property
    def connection(self) -> global___Connection: ...
    def __init__(
        self,
        *,
        connection: global___Connection | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["connection", b"connection"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["connection", b"connection"]) -> None: ...

global___IPsecLoadConnReq = IPsecLoadConnReq

@typing_extensions.final
class IPsecLoadConnResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.str
    def __init__(
        self,
        *,
        success: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["success", b"success"]) -> None: ...

global___IPsecLoadConnResp = IPsecLoadConnResp

@typing_extensions.final
class IPsecUnloadConnReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___IPsecUnloadConnReq = IPsecUnloadConnReq

@typing_extensions.final
class IPsecUnloadConnResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.str
    def __init__(
        self,
        *,
        success: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["success", b"success"]) -> None: ...

global___IPsecUnloadConnResp = IPsecUnloadConnResp
