"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-License-Identifier: Apache-2.0
Copyright (c) 2022 Dell Inc, or its subsidiaries.
{C} Copyright 2022 Pensando Systems Inc. All rights reserved
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Uuid(google.protobuf.message.Message):
    """A universally unique identifier (UUID) is a 128-bit label
    When generated according to the standard methods, UUIDs are, for practical purposes, unique.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    """The value of the UUID"""
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___Uuid = Uuid
